### ISSUE TITLE
spo app add does not return App Id only anymore

### ISSUE THREAD

**Issue by Laul0** [pnp/action-cli-deploy#11]
This is a related issue with pnp/cli-microsoft365#2080

Maybe include the solution that consist to replace `UniqueId` string from the returned result of the `spo app add` command.

**Comment by waldekmastykarz** [comment]
Thanks for reporting the issue. Let's resolve the issue with CLI first and based on that handle this issue, ok?

**Comment by waldekmastykarz** [comment]
We'll fix it in the CLI

**Comment by FredrikEkstroem** [comment]
Hi, was this fixed or will it be fixed in CLI? I currently added a local copy and added
JSON.parse(appId).UniqueId to get it to work

**Comment by milanholemans** [comment]
> Hi, was this fixed or will it be fixed in CLI? I currently added a local copy and added JSON.parse(appId).UniqueId to get it to work

Hi @FredrikEkstroem

The default behavior of the CLI is to always return the entire result we get from the API. So if you want to retrieve the `UniqueId`, you should read this property from the result object.
![image](https://user-images.githubusercontent.com/11723921/203120859-0aafc107-bda7-4900-ae8f-afc1e39bacdb.png)

Another way, if you really want the `UniqueId` only is to use `--output text` mode. This will return the ID only.
![image](https://user-images.githubusercontent.com/11723921/203121040-139069c9-9f79-4a12-9aa2-3953922d288f.png)


Does this answer your question?

**Comment by FredrikEkstroem** [comment]
@milanholemans so I guess there are 2 ways to fix this Github Action, to me it looks like it's currently broken? 

https://github.com/pnp/action-cli-deploy/blob/master/src/main.ts 

should be updated to
```typescript
//row 27
appId = await executeCLIMicrosoft365Command(`spo app add -p ${appFilePath} --scope sitecollection --appCatalogUrl ${siteCollectionUrl} ${overwrite} --output text`, true);

//row 31
appId = await executeCLIMicrosoft365Command(`spo app add -p ${appFilePath} ${overwrite} --output text`, true);
```
alternatively
```typescript
//row 28
await executeCLIMicrosoft365Command(`spo app deploy --id ${JSON.parse(appId).UniqueId} --scope sitecollection --appCatalogUrl ${siteCollectionUrl} ${skipFeatureDeployment}`);

//row 32
await executeCLIMicrosoft365Command(`spo app deploy --id ${JSON.parse(appId).UniqueId} ${skipFeatureDeployment}`);
```

**Comment by milanholemans** [comment]
Hi @FredrikEkstroem you can completely ignore my last comment. I thought I was replying to an issue in the regular CLI repo (my bad).

You are right, this seems like a bug, let's create an issue for this (#18).
Thank you for reporting this!
