### ISSUE TITLE
Dependabot alerts

### ISSUE THREAD

**Issue by crivasestrada** [pnp/action-cli-deploy#14]
Hi,
I would like to make a request about vulnerabilities detect in the security scan.
I have clone this repository and I haved passed a security scan. The Dependabot alerts show 3 vulnerabilities related to dependencies version included in the package-lock.json:

- path-parse version 1.0.6 --> fixed vulnerability in version 1.0.7 or later
- @actions/core version 1.2.1-->fixed vulnerability in version 1.2.6 or later
- minimist version 0.0.8 --> fixed vulnerability in version 0.2.1 or later

Please, I would like to know if there is any plan to upgrade these dependencies version in orden to eliminate le vulnerabilities.

Thanks in advanced

**Comment by garrytrinder** [comment]
Thank you @crivasestrada we will definitely look to resolve these vulnerabilities.

**Comment by garrytrinder** [comment]
Thank you for raising this issue @crivasestrada 👍🏻 

We have just released a new version, v2.0.1, that addresses these vulnerabilities.
