### ISSUE TITLE
`spo app add` not returning `UniqueId` anymore.

### ISSUE THREAD

**Issue by milanholemans** [pnp/action-cli-deploy#18]
Originates from: https://github.com/pnp/action-cli-deploy/issues/11#issuecomment-1322358369

Apparently we broke the GitHub action flow by defining the default `output` in the CLI runtime. Because of this issue: https://github.com/pnp/cli-microsoft365/issues/3445

Our default `output` value used to be `undefined`, by refactoring this to `json`, the command will now return the entire app object instead of just the ID.

https://github.com/pnp/cli-microsoft365/blob/e42aed1530b6755b2485a944bbd9a251aac3fddb/src/m365/spo/commands/app/app-add.ts#L127-L132

Therefore these lines of code will fail:

https://github.com/pnp/action-cli-deploy/blob/6014072c7a52ec213896ba46e792ddef1b3e971e/src/main.ts#L27-L28

https://github.com/pnp/action-cli-deploy/blob/6014072c7a52ec213896ba46e792ddef1b3e971e/src/main.ts#L31-L32

**Comment by milanholemans** [comment]
@pnp/cli-for-microsoft-365-maintainers I assume we should just parse the JSON object and read the `UniqueId` property of it right?

**Comment by Adam-it** [comment]
@milanholemans yes I agree. parse and return the UniqueId so that we keep the previous behavior 👍

**Comment by milanholemans** [comment]
Hi @FredrikEkstroem, the issue should have been fixed now.
Many thanks for reporting this bug! Much appreciated!

**Comment by FredrikEkstroem** [comment]
@milanholemans I can confirm it works now.
