### ISSUE TITLE
Upcoming bug: Update option names to align v6 naming

### ISSUE THREAD

**Issue by milanholemans** [pnp/action-cli-deploy#19]
Because of this issue https://github.com/pnp/cli-microsoft365/issues/2696, the GitHub action will fail because we will introduce some breaking changes to `spo app add` and `spo app deploy`.

For both commands, the option `scope` will be renamed to `appCatalogScope`. We should fix this when `v6` of the CLI is released.

**Comment by milanholemans** [comment]
@pnp/cli-for-microsoft-365-maintainers we should also consider this upcoming bug.

**Comment by Adam-it** [comment]
I think you are also right here as well 👍 good catch 👍 lets be sure to have the PR ready to merge it with the release of v6

**Comment by FredrikEkstroem** [comment]
A question related to this change, when running pnp/action-cli-login@v2.2.1 without CLI_VERSION specified the latest CLI will be installed? And when 6.0 is available in npm, the old versions will break if not updated to pnp/action-cli-login@2.0.3? Or will the --scope still be there marked as deprecated for a while?

**Comment by milanholemans** [comment]
> A question related to this change, when running pnp/action-cli-login@v2.2.1 without CLI_VERSION specified the latest CLI will be installed?

Yes correct!

> And when 6.0 is available in npm, the old versions will break if not updated to pnp/action-cli-login@2.0.3? Or will the --scope still be there marked as deprecated for a while?

Since the latest version of the CLI will be installed, the GitHub action will indeed fail because we renamed the options in `v6`. One time per year we release a new major version which contains breaking changes, so once per year we can remove deprecated options etc. However now you are talking about the `pnp/action-cli-login` repo. That repo will not be suffering from the breaking changes, only this repo will.

**Comment by waldekmastykarz** [comment]
Good catch! We should bump the major version of this action and in the docs clearly indicate that it can be used only with v6. For older versions of the CLI folks should use the v2 of this action.
