### ISSUE TITLE
Flush SPFX Cache on Deploy to tenant 

### ISSUE THREAD

**Issue by michaelsoriano** [pnp/action-cli-deploy#27]
This is more of a question rather than an actual issue. We are experiencing caching issues whend deploying SPFX app to SharePoint similar to https://github.com/SharePoint/sp-dev-docs/issues/8915. I'm wondering if there is something that can be done via this action or m365 cli - to flush all existing assets before deploying (contents of .spkkg file). Thanks.

**Comment by waldekmastykarz** [comment]
That would be a great addition for sure @michaelsoriano. Unfortunately, I don't think there's any API that we could use for this. Let's track the conversation on the issue you mentioned and should an ability to flush cache in SharePoint become available, we'll absolutely add it to the CLI.
