### ISSUE TITLE
Publish the GitHub action on the marketplace

### ISSUE THREAD

**Issue by VelinGeorgiev** [pnp/action-cli-deploy#3]
We will have to perform few things to achieve this:
- Research how to publish GitHub action on the Marketplace
- Release version v1 (with tag included) of the GitHub action
- Publish the GitHub action on the marketplace

**Comment by anoopt** [comment]
@VelinGeorgiev - Hope the instructions mentioned in GitHub Actions [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/publishing-actions-in-github-marketplace) are helpful to achieve the above requests.

**Comment by VelinGeorgiev** [comment]
Thanks Anoop I will try to process this asap!

**Comment by VelinGeorgiev** [comment]
Closing this. The action is now published at https://github.com/marketplace/actions/office-365-cli-deploy-app.
