### ISSUE TITLE
Appid is required

### ISSUE THREAD

**Issue by eugenepeterpalacios** [pnp/action-cli-deploy#39]
Failure logging in to Tenant using authType of password

![image](https://github.com/user-attachments/assets/62665668-dcbb-422f-9b8a-47e21bf10322)

**Comment by martinlingstuyl** [comment]
Hi @eugenepeterpalacios, this is due to the [recent removal](https://www.youtube.com/watch?v=VNgc4k_gCT0) of the PnP Entra ID Application that was used to sign in. 

You'll now need to create an app registration on your tenant to sign in succesfully.

@Adam-it has you covered on how to do that in this fantastic video:
https://www.youtube.com/watch?v=XFG8gVGvXpA

As you are using the CLI in a GitHub action workflow I would run m365 setup locally or create the application manually, and then register the ApplicationId in github as a variable.

Let me know if it worked out for you!

**Comment by eugenepeterpalacios** [comment]
Hi @martinlingstuyl - thanks for the reply. Now I am getting this issue:

![image](https://github.com/user-attachments/assets/feaa157e-6048-4b38-9f3b-7180035474d9)

**Comment by martinlingstuyl** [comment]
If I read the error message I'm assuming you are somehow logging in using the client secret authentication flow, instead of username/password. And Client Secret flow is indeed not supported on SharePoint. Could you verify that you are signing into the CLI correctly?

**Comment by eugenepeterpalacios** [comment]
Hi @martinlingstuyl - ok got it. I tried reverting back to the authType of password and got this issue. 

![image](https://github.com/user-attachments/assets/c07c57d9-d275-40ff-aa1f-24e9d04c84c1)

If I remove the appId, it errors out asking for the appId. If I add the appId, then this shows up.

**Comment by martinlingstuyl** [comment]
Hi @eugenepeterpalacios, could you try if this fixed when you add the tenant id using the `--tenant` option?

**Comment by martinlingstuyl** [comment]
And may I ask how you created the entra app registration in your tenant? Manually or using `m365 setup`?

**Comment by eugenepeterpalacios** [comment]
Hi @martinlingstuyl . same issue. it was asking for this. We created the app registration manually. 

![image](https://github.com/user-attachments/assets/b128a56c-5fbc-4a85-9e3a-bacbe4e250be)

**Comment by martinlingstuyl** [comment]
Ok @eugenepeterpalacios, I think you forgot to enable Public Client Flows on the app registration (On the "Authentication" blade)

![image](https://github.com/user-attachments/assets/6c9030a0-17ee-4449-8fc2-87aa70da3eff)

The password flow wont work without it. Same story for the Device code flow by the way. If I disable it I get the same error as you.

Please check our guide if you didn't miss something else by chance:
https://pnp.github.io/cli-microsoft365/user-guide/using-own-identity

**Comment by eugenepeterpalacios** [comment]
Ok. Thanks @martinlingstuyl. I'll request this to be enabled. I'll update you on this. Thank you!

**Comment by martinlingstuyl** [comment]
Hi @eugenepeterpalacios, Did you already get response on your request?

**Comment by eugenepeterpalacios** [comment]
Hi @martinlingstuyl - good day and apologies for the late reply. 

I am now getting this issue. 

Error: invalid_grant: AADSTS65001: The user or administrator has not consented to use the application. Send an interactive authorization request for this user and resource. 

According to the guide, it does not need to be consented. 

![image](https://github.com/user-attachments/assets/e5801029-650c-47ba-9463-e897f8d20b47)

**Comment by martinlingstuyl** [comment]
Hi @eugenepeterpalacios, if you do not give admin consent, the application will want to ask for consent while logging in the first time. If you would sign in using the device code flow, you would get this consent flow immediately. In your case you are using the `password` authType from within a GitHub Action. The password flow does not have an interactive experience, it does not open a browser window, so it cannot direct the user to the consent flow. And even if it did, you are running in GitHub actions, so it wont be able to give that consent, as it's an automated process. Hence it fails.

So you will either need to grant an admin consent beforehand of sign in once with the same user account locally using device code flow, so you can give consent.

**Comment by eugenepeterpalacios** [comment]
Hi @martinlingstuyl  - thanks for this. So would it be possible to allow it on initial, then remove the admin consent once done? Kindly advise.

**Comment by martinlingstuyl** [comment]
@eugenepeterpalacios if you expressly want to avoid an admin consent, I'd go for a user consent: just open a terminal on your local machine. Run `m365 login --authType deviceCode --appId <appId>` and sign into the application and give your consent with the account that is used in the GH action.

I'd personally just give the admin consent in this case. But from a security standpoint it could be a good argument that users need to consent themselves whether an application may run operations against M365 services on their behalf. Even with an application that's probably not going to be used widely in your organization.

**Comment by martinlingstuyl** [comment]
If the GitHub action works now, do let us know so we can close this issue...

**Comment by eugenepeterpalacios** [comment]
Hi @martinlingstuyl - will do. I will update this thread immediately. thank you!

**Comment by eugenepeterpalacios** [comment]
Hi @martinlingstuyl  - I have already requested for this app to be approved thru user consent. Will close this issue already. Thank you for your assistance on this!
