### ISSUE TITLE
--skipFeatureDeployment not included in spo app deploy command on Windows

### ISSUE THREAD

**Issue by FTsbrown** [pnp/action-cli-deploy#4]
When this action is used to deploy a solution to SharePoint tenant from a Windows task runner the `skipFeatureDeployment` flag is not included in the command. This is due to the appId parameter including a return carriage character that escapes the string. 

### Steps to reproduce

1. Include this action in a GitHub Action using the windows-latest runner.

2. set `SKIP_FEATURE_DEPLOYMENT` to true.

The following log shows the --skipFeatureDeployment flag being printed on the following line rather than being included in the deploy command.

```
/usr/local/bin/o365 spo app add -p solution.sppkg --overwrite
 ***app-id***

/usr/local/bin/o365 spo app deploy --id ***app-id***
 --skipFeatureDeployment
```

**Comment by waldekmastykarz** [comment]
@anoopt @VelinGeorgiev do you know if there is a way to process the output of the CLI before returning it from the action?

It seems like the issue @FTsbrown mentioned is caused by the CLI returning the app-id with a line break at the end which then breaks the following commands.

**Comment by anoopt** [comment]
@waldekmastykarz @VelinGeorgiev  the PR submitted for this by @FTsbrown is brilliant and solves the issue. If needed, before returning the output ( line number 35 ), we can clean the `appId` using a regular expression.

**Comment by waldekmastykarz** [comment]
@anoopt if we can remove the trailing line break in the CLIs output when used in an action, then we wouldn't need to work around it and use implicit solutions like a specific order of options which could get easily lost.

Could you submit a fix for the action that cleans the `appId` value returned by the action?

**Comment by VelinGeorgiev** [comment]
Thank  you for the nice discussion. I will mark this as work in progress.

**Comment by waldekmastykarz** [comment]
@anoopt removing the line break in the CLI output before returning it would fix the issue experienced by @FTsbrown, right? In that case, shall we close #5 in favor of the change you proposed?

**Comment by anoopt** [comment]
Yes @waldekmastykarz . If the `appid` returned by `app add` has no line break then it will fix the issue submitted by @FTsbrown .

Also after that, do we still need to clean the `appId` that is returned by the deploy action?

**Comment by waldekmastykarz** [comment]
Yes, if the returned output is problematic in actions, then we should clean it up so that the different actions can be chained easily

**Comment by anoopt** [comment]
Thank you @waldekmastykarz . PR on its way :)

**Comment by waldekmastykarz** [comment]
Thank you @anoopt! 👏

**Comment by VelinGeorgiev** [comment]
Hey @FTsbrown , @anoopt , @waldekmastykarz , 

Thank you all for the cooperation! It is great to have you helping this initiative.

I tested and released the fix to the [marketplace this morning](https://github.com/marketplace/actions/office-365-cli-deploy-app?version=v1.0.1). Please give it a try and let me know if you sill experience issues. Please note that you have to bump up the version of the cli-deploy action to `v1.0.1` like:

```
- name: Office 365 CLI Deploy App
  uses: pnp/action-cli-deploy@v1.0.1
```
