### ISSUE TITLE
Site collection admins are not allowed to deploy

### ISSUE THREAD

**Issue by AshikPaul42** [pnp/action-cli-deploy#8]
I have some site collections that have site collection level app catalog(mysite/appcatalog   not   apps/appcatalog) and I want to deploy using pnp action, but Office 365 CLI only allows tenant admins to deploy. 

Please allow site collection admins to deploy to the site that he owns.

**Comment by VelinGeorgiev** [comment]
@AshikPaul42, have you tried to deploy to a site collection app catalog when you are logged in with your site collection admin account? Can you share the error you are getting?

**Comment by AshikPaul42** [comment]
Thank you @VelinGeorgiev for the quick response.  

I have attached a screenshot of the issue. The comment says only tenant admin can log in or only if consent is issued. 

My situation is I have no way to contact the admin team and grant me consent or access to the tenant admin portal. 
So I found another way to do the same by using a PowerShell module. 

Very useful action but I hope it will allow non-tenant admins to deploy an app to sitecollection level scope sites.

Great work. Thank you 😍

![image](https://user-images.githubusercontent.com/64515863/86272066-9f260880-bbeb-11ea-8f3a-0c310d2093ab.png)

**Comment by VelinGeorgiev** [comment]
@AshikPaul42 thank you very much for your response. 

Yes, you are correct. It is not possible to login to the CLI without approved Azure AD app. Currently PowerShell can workaround that using old Azure Access Control (ACS) Authentication with AppOnlyAccessToken. 

Unfortunately, the Azure Access Control (ACS) is considered by the CLI maintainers as legacy and we do not expect Microsoft to support it in long term so we have not implemented it in the CLI.
